import os

CPU_ALERT_PERCENT = float(os.getenv("CPU_ALERT_PERCENT", 85))
RAM_ALERT_PERCENT = float(os.getenv("RAM_ALERT_PERCENT", 90))
DISK_ALERT_PERCENT = float(os.getenv("DISK_ALERT_PERCENT", 95))

PROCESS_POLL_INTERVAL = int(os.getenv("PROCESS_POLL_INTERVAL", 15))
NETWORK_POLL_INTERVAL = int(os.getenv("NETWORK_POLL_INTERVAL", 10))
HEALTH_POLL_INTERVAL = int(os.getenv("HEALTH_POLL_INTERVAL", 20))

DOWNLOADS_SCAN_INTERVAL_MINUTES = int(os.getenv("DOWNLOADS_SCAN_INTERVAL_MINUTES", 30))
DOWNLOADS_MAX_AGE_DAYS = int(os.getenv("DOWNLOADS_MAX_AGE_DAYS", 30))
DOWNLOADS_MAX_FILES = int(os.getenv("DOWNLOADS_MAX_FILES", 100))

SUSPICIOUS_PORTS = [
    int(p) for p in os.getenv("SUSPICIOUS_PORTS", "4444,6666,31337,1337,9001").split(",")
]
